In [1]:
import pandas as pd

items = pd.read_csv("item_detail.csv")
persona = pd.read_csv("persona.csv")
user_statistic = pd.read_csv("user_statistic.csv")
user_statistic_num = pd.read_csv("user_statistic_num.csv")

In [2]:
items

,item_id,asin,title,description,category,rating,price,director,poster_url
0,0,0000143588,"Barefoot Contessa (with Ina Garten), Entertain...",Barefoot Contessa Volume 2: On these three dis...,"['Movies & TV', 'Movies', 'Documentary', 'Fami...",0.0,74.95,NaN,NaN
1,1,0001526863,Steve Green: Hide 'em in Your Heart: 13 Bible ...,Steve Green: Hide 'em in Your Heart: 13 Bible ...,"['Movies & TV', 'Christian Video', 'Bible', 'M...",0.0,0.00,NaN,NaN
2,2,0001527665,Peace Child VHS,[],"['Movies & TV', 'Art House & International', '...",0.0,0.00,Rolf Forsberg,https://m.media-amazon.com/images/M/MV5BMTA1Mj...
3,3,0005000009,Where Jesus Walked VHS,An early movie edition of the life of Jesus.,"['Movies & TV', 'Christian Video', 'General', ...",0.0,0.00,Rolf Forsberg,https://m.media-amazon.com/images/M/MV5BZmU4Zj...
4,4,0005019281,An American Christmas Carol VHS,"In Depression-era New England, a miserly busin...","['Movies & TV', 'Movies', 'Comedy', 'Drama', '...",0.0,0.00,Eric Till,https://m.media-amazon.com/images/M/MV5BZDZkOT...
...,...,...,...,...,...,...,...,...,...
86673,86595,NaN,NaN,NaN,[],0.0,0.00,NaN,NaN
86674,86595,NaN,NaN,NaN,[],0.0,0.00,NaN,NaN
86675,86595,NaN,NaN,NaN,[],0.0,0.00,NaN,NaN
86676,86595,NaN,NaN,NaN,[],0.0,0.00,NaN,NaN
86677,86595,NaN,NaN,NaN,[],0.0,0.00,NaN,NaN

In [3]:
persona

,user_id,taste,reason
0,0,Horror and Thriller Enthusiast|Comedy and Dram...,User consistently rates horror and thriller mo...
1,1,Drama enthusiast|Crime and thriller lover,User consistently rates products with genres l...
2,2,Family-friendly and heartwarming|Biographical ...,The user consistently rates movies with themes...
3,3,Family-friendly Entertainment Enthusiast|Horro...,User consistently rates family-friendly movies...
4,4,Thriller and Drama Enthusiast|Horror and Myste...,User consistently rates products in the thrill...
5,5,Classic Film Enthusiast|Documentary Buff,User consistently rates classic drama and crim...
6,6,Family-friendly and Adventure-driven|Thrilling...,User consistently rates movies with themes of ...
7,7,Drama enthusiast with a preference for interna...,User consistently rates drama films from vario...
8,8,Classic Film Enthusiast|Sci-Fi and Fantasy Fan,User consistently rates classic movies from va...
9,9,Horror and Thriller Enthusiast|Action and Dram...,User consistently rates horror and thriller mo...

In [4]:
user_statistic

   user_id  activity  diversity  conformity
0        0         3          2           3
1        1         3          2           2
2        2         3          3           1
3        3         3          2           1
4        4         2          3           1
5        5         2          2           3
6        6         2          1           2
7        7         1          3           3
8        8         1          3           1
9        9         1          1           2

In [5]:
user_statistic_num

   user_id  activity_num  diversity_num  deviation
0        0          3753            126   0.206373
1        1          2114            131   0.250846
2        2          2081            144   0.465564
3        3          1950            126   0.570127
4        4          1844            155   0.579432
5        5          1798            133   0.142499
6        6          1758            115   0.374315
7        7          1715            149   0.231941
8        8          1660            149   0.552099
9        9          1656            110   0.417461

In [7]:
persona.loc[0]

user_id                                                    0
taste      Horror and Thriller Enthusiast|Comedy and Dram...
reason     User consistently rates horror and thriller mo...
Name: 0, dtype: object

In [8]:

from pymongo import MongoClient

client = MongoClient("mongodb://localhost:27017")
mydb = client["items"]  # 데이터베이스 이름
mycoll = mydb["user"]  # 컬렉션 이름

In [13]:
one_doc = mycoll.find_one({"_id": "1"})

one_doc

{'_id': '1',
 'reviewerID': 'A3478QRKQDOPQ2',
 'password': '1234',
 'items': [{'itemnum': 9284,
   'asin': 'B000051S5P',
   'reviewText': "it sucks, but you can't watch the regular movie, at least if you get the directors cut version like i did or whatever-not reccomendable..i wanted to see the movie-not them talking over the movies creation..urgh",
   'overall': 1.0,
   'summary': "it isn't really the film, it is a review commentary of the film",
   'unixReviewTime': 1316649600,
   'predicted_genre': ['Comedy', 'Drama', 'Family']},
  {'itemnum': 5255,
   'asin': '6304211740',
   'reviewText': 'well it was quite a likeable film really..pretty g-rated except for the insane wife.. the love story is very very lovely..',
   'overall': 5.0,
   'summary': 'this was quite a great film',
   'unixReviewTime': 1316822400,
   'predicted_genre': ['Drama', 'Romance']},
  {'itemnum': 73361,
   'asin': 'B001H8BU4Y',
   'reviewText': "and it didn't skip on my computer, only on my vcr..so it wasn't fault of the product i guess when i retried it",
   'overall': 5.0,
   'summary': 'its not good movie really to me, but the seller shipped it fine',
   'unixReviewTime': 1362614400,
   'predicted_genre': ['Drama', 'Romance', 'Family']},
  {'itemnum': 1,
   'asin': '0001527665',
   'reviewText': 'really happy they got evangelised .. spoiler alert==happy ending liked that..since started bit worrisome... but yeah great stories these missionary movies, really short only half hour but still great',
   'overall': 5.0,
   'summary': 'great',
   'unixReviewTime': 1362960000,
   'predicted_genre': ['Drama', 'History', 'Family']},
  {'itemnum': 14316,
   'asin': 'B0001CLZJC',
   'reviewText': 'average christian film, but good to have  these around and collect these for sabbath watching sso yeaha ok so,,. ..',
   'overall': 4.0,
   'summary': 'ok',
   'unixReviewTime': 1362960000,
   'predicted_genre': ['Drama', 'Family', 'Fantasy']},
  {'itemnum': 62483,
   'asin': 'B0001EQI7E',
   'reviewText': 'one of those end of world movies pretty good ... so yeah good to add to collection if you like maybe',
   'overall': 4.0,
   'summary': 'pretty good',
   'unixReviewTime': 1362960000,
   'predicted_genre': ['Drama', 'Thriller', 'Sci-Fi']},
  {'itemnum': 14532,
   'asin': 'B0001KREGW',
   'reviewText': 'i did not get it, it may have had symbolism but i fell asleep on it and it was too weird in general to be interesting at least for me',
   'overall': 1.0,
   'summary': 'not that good',
   'unixReviewTime': 1363564800,
   'predicted_genre': ['Fantasy', 'Horror', 'Thriller']},
  {'itemnum': 186,
   'asin': '0783225911',
   'reviewText': 'i think she tried to convert him and forgot if she won him over you will have to see it to find out, i think was good one to my memory',
   'overall': 4.0,
   'summary': 'good evangelism story',
   'unixReviewTime': 1393891200,
   'predicted_genre': ['Western', 'Drama', 'Action']},
  {'itemnum': 1009,
   'asin': '6300158683',
   'reviewText': 'kind of weird one though..? not as classic or normal/sane  or inspiring as others i have seen.. . . ..',
   'overall': 3.0,
   'summary': 'missionary film',
   'unixReviewTime': 1393891200,
   'predicted_genre': ['Drama', 'Romance', 'Film-Noir']},
  {'itemnum': 2348,
   'asin': '6302213304',
   'reviewText': "I thought was Christian film and so wasn't and wasn't even good regular film so dumb haha for real",
   'overall': 1.0,
   'summary': "... was Christian film and so wasn't and wasn't even good regular film so dumb haha for",
   'unixReviewTime': 1393891200,
   'predicted_genre': ['Adventure', 'Documentary', 'Family']},
  {'itemnum': 41418,
   'asin': 'B007XIO8KA',
   'reviewText': "I thought was Christian film and so wasn't and wasn't even good regular film so dumb haha for real",
   'overall': 1.0,
   'summary': "... was Christian film and so wasn't and wasn't even good regular film so dumb haha for",
   'unixReviewTime': 1393891200,
   'predicted_genre': ['Adventure', 'Drama', 'Thriller']},
  {'itemnum': 71318,
   'asin': 'B0012Q3T3Q',
   'reviewText': 'shows them exploring and giving talks at churches in between, pretty cool idea, glad they filmed it-I like to see a bit of what missionary trips are like never got to go on one.',
   'overall': 4.0,
   'summary': 'its good missionary film',
   'unixReviewTime': 1394755200,
   'predicted_genre': ['Adventure', 'Biography', 'Documentary']},
  {'itemnum': 3495,
   'asin': '6303118127',
   'reviewText': 'yeah I collect these for Sabbath viewing and are usually all very good with good Christian points in them, thanks.',
   'overall': 4.0,
   'summary': 'good classic for the christian collection',
   'unixReviewTime': 1397520000,
   'predicted_genre': ['Biography', 'Drama', 'History']},
  {'itemnum': 2419,
   'asin': '6302274001',
   'reviewText': "pretty cute love story happy but sad ending but that's life..nice perseverance although sometimes made me think if she listened to others counsel maybe would have never happened but then missing out on living your dreams is saddest irony as well so who knows sometimes",
   'overall': 3.0,
   'summary': "pretty cute love story happy but sad ending but that's ...",
   'unixReviewTime': 1432252800,
   'predicted_genre': ['Family', 'Musical', 'Drama']},
  {'itemnum': 9941,
   'asin': 'B00005JLOT',
   'reviewText': "I thought was nice movie but sad ending, seemed magical though the prospect of being in love together and in love forever..she was stupid girl or he was stupid to be bipolar to her he stopped her from drinking water urgh then wanted her to ok then you're gonna be single forever bipolar guy",
   'overall': 4.0,
   'summary': 'I thought was nice movie but sad ending',
   'unixReviewTime': 1432252800,
   'predicted_genre': ['Adventure', 'Family', 'Fantasy']},
  {'itemnum': 15138,
   'asin': 'B0002AAOEA',
   'reviewText': "Just love this story its so special it acts like evangelists are good things like no other-and I am one so I thought that was so happy and receptive to be good influence like that-and its cool little short 70's quirky cartoon and since I was born 79 and it 78 haha its kind of cool to me",
   'overall': 5.0,
   'summary': 'Just love this story its so special it acts like evangelists ...',
   'unixReviewTime': 1432252800,
   'predicted_genre': ['Adventure', 'Drama', 'Family']},
  {'itemnum': 81550,
   'asin': 'B00C7BZGCM',
   'reviewText': "some of these films are ok for Sabbath sometimes they seem a bit worldly so they can relate to non Christians but then can inspire and evangelise them too-so if that's what you need that's cool and also shows hopefulness of maybe how evangelism can help and be done..forgot some of these plots but we're pretty good films all of them I think ok to collect for Sabbath viewing like I say the different ones in series-maybe look for sample online youtube if on there or billy graham movie site to see what are like first and if sounds/looks good then get it cuz good to see more than once maybe if like",
   'overall': 4.0,
   'summary': "... evangelise them too-so if that's what you need that's cool and also shows hopefulness of maybe how evangelism can ...",
   'unixReviewTime': 1432252800,
   'predicted_genre': ['Drama', 'Biography']},
  {'itemnum': 1671,
   'asin': '6301640780',
   'reviewText': 'it seemed like there was nothing spiritual in it, so much time was on other stuff they had like 20 seconds mention of the jesus part only?! I gave it away too frustrating waiting for good inspiring christian part ..not a good for Sabbath film haha, more like if have insomnia and want to be bored regular type film..those one star regular kind though',
   'overall': 1.0,
   'summary': 'it seemed like there was nothing spiritual in it',
   'unixReviewTime': 1448668800,
   'predicted_genre': ['Drama', 'Family', 'Biography']},
  {'itemnum': 28270,
   'asin': 'B001AYJ2Y0',
   'reviewText': 'was a good version, better than older one maybe..pretty cool story about man on search for god and salvation and great symbolism in names of who he meets like evangelist-who sends him on the right path..the book is good too.',
   'overall': 4.0,
   'summary': 'was a good version, better than older one maybe',
   'unixReviewTime': 1448668800,
   'predicted_genre': ['Drama', 'Family', 'Fantasy']},
  {'itemnum': 3554,
   'asin': '6303148263',
   'reviewText': "I don't know if I really liked it? I think I felt it was hard to follow maybe if I see it again I will get it though who knows..",
   'overall': 2.0,
   'summary': "I don't know if I really liked it? I think I felt it was hard ...",
   'unixReviewTime': 1448668800,
   'predicted_genre': ['Drama', 'Fantasy', 'Family']},
  {'itemnum': 26572,
   'asin': 'B0012Q3T40',
   'reviewText': 'I enjoyed watching these on Sabbath-very cool idea stories of missionaries live on the field of saving souls..adventuresome too going all these places and learning of cultures',
   'overall': 5.0,
   'summary': 'I enjoyed watching these on Sabbath-very cool idea stories of missionaries ...',
   'unixReviewTime': 1448668800,
   'predicted_genre': ['Adventure', 'Documentary', 'Drama']},
  {'itemnum': 81551,
   'asin': 'B00C7BZG8Q',
   'reviewText': 'story about man looking for father in Amsterdam Europe and has Christian themes',
   'overall': 4.0,
   'summary': 'Four Stars',
   'unixReviewTime': 1448668800,
   'predicted_genre': ['Drama', 'Biography', 'Crime']},
  {'itemnum': 44604,
   'asin': 'B00C7BZGAO',
   'reviewText': 'pretty good about young man rebelling with father and Christian topics',
   'overall': 3.0,
   'summary': 'Three Stars',
   'unixReviewTime': 1448668800,
   'predicted_genre': ['Drama', 'Biography']},
  {'itemnum': 541,
   'asin': '078885996X',
   'reviewText': 'good film with lots of nice music, one of better versions of christmas carol music wise.',
   'overall': 4.0,
   'summary': 'Four Stars',
   'unixReviewTime': 1452470400,
   'predicted_genre': ['Animation', 'Family', 'Musical']},
  {'itemnum': 64232,
   'asin': 'B00097E6OA',
   'reviewText': "seemed pretty good. I mean I like Christian music and maybe books sometimes better than films, but they are still to be cherished even though they are few and not always the best..i still cherish them for Sabbath, they are still good to collect for watching on sundays to keep Sabbath holy and fun for that-this is kind of one of those classics wasn't too bad as far as Christian or any films for that matter goes..you know movies are always a bit dumb just how is..but watchable when in mood for sure with great points and everything you know that are very inspiring if let be",
   'overall': 4.0,
   'summary': 'good!',
   'unixReviewTime': 1467417600,
   'predicted_genre': ['Comedy', 'Drama', 'Mystery']},
  {'itemnum': 55941,
   'asin': '6300137279',
   'reviewText': "I really liked this workout before one if few ones I did like to do-most seem boring-can't it be reissued??",
   'overall': 5.0,
   'summary': 'SHOULD BE REISSUED WAS REALLY FUN',
   'unixReviewTime': 1468886400,
   'predicted_genre': ['Adult', 'Reality-TV']},
  {'itemnum': 7108,
   'asin': '630573240X',
   'reviewText': 'ok',
   'overall': 3.0,
   'summary': 'good',
   'unixReviewTime': 1470096000,
   'predicted_genre': ['Drama', 'Mystery', 'Thriller']},
  {'itemnum': 7122,
   'asin': '630574999X',
   'reviewText': 'ok',
   'overall': 3.0,
   'summary': 'good',
   'unixReviewTime': 1470096000,
   'predicted_genre': ['Drama', 'Mystery', 'Thriller']},
  {'itemnum': 15247,
   'asin': 'B0002ERWVE',
   'reviewText': 'pretty cool Christian sitcom one of rarer ones ever made like highway to heaven and this is all I know of that are so I think is pretty cool idea-on these whats cool is that they really try to reach out to all types of  struggling people on these episodes-to try to inspire and relate very kind effort I think and hope people will discover them that are types that relate-their are stories about and for runways prostitutes aids all kinds of issues in life and these angels are assigned to try to help people and so its nice ideas in it',
   'overall': 4.0,
   'summary': '-nice sitcom that can encourage people struggling or anyone',
   'unixReviewTime': 1470096000,
   'predicted_genre': ['Drama', 'Family', 'Fantasy']},
  {'itemnum': 16348,
   'asin': 'B0007CEXTK',
   'reviewText': 'great',
   'overall': 4.0,
   'summary': 'great positive christian type sitcom',
   'unixReviewTime': 1470096000,
   'predicted_genre': ['Drama', 'Family', 'Fantasy']},
  {'itemnum': 18914,
   'asin': 'B000BYRCGA',
   'reviewText': 'good',
   'overall': 3.0,
   'summary': 'good',
   'unixReviewTime': 1470096000,
   'predicted_genre': ['Drama', 'Family', 'Fantasy']},
  {'itemnum': 22509,
   'asin': 'B000LV6W0A',
   'reviewText': 'good',
   'overall': 4.0,
   'summary': 'ok',
   'unixReviewTime': 1470096000,
   'predicted_genre': ['Drama', 'Family', 'Fantasy']},
  {'itemnum': 29395,
   'asin': 'B001FOPQN6',
   'reviewText': 'good',
   'overall': 3.0,
   'summary': 'good',
   'unixReviewTime': 1470096000,
   'predicted_genre': ['Drama', 'Family', 'Romance']},
  {'itemnum': 30161,
   'asin': 'B001KVZ6ES',
   'reviewText': 'ok',
   'overall': 3.0,
   'summary': 'ok',
   'unixReviewTime': 1470096000,
   'predicted_genre': ['Drama', 'Crime', 'Family']},
  {'itemnum': 46249,
   'asin': 'B00ENFS0FK',
   'reviewText': 'good',
   'overall': 3.0,
   'summary': 'good',
   'unixReviewTime': 1470096000,
   'predicted_genre': ['Drama', 'Family', 'Fantasy']},
  {'itemnum': 53690,
   'asin': 'B015S4DS1K',
   'reviewText': 'ok',
   'overall': 3.0,
   'summary': 'ok',
   'unixReviewTime': 1470096000,
   'predicted_genre': ['Drama', 'Crime', 'Family']},
  {'itemnum': 68431,
   'asin': 'B000MCIADK',
   'reviewText': 'ok but make sure to get the right language one',
   'overall': 3.0,
   'summary': 'ok',
   'unixReviewTime': 1470096000,
   'predicted_genre': ['Drama', 'Biography', 'Family']},
  {'itemnum': 81830,
   'asin': 'B00D29AAJM',
   'reviewText': 'pretty good',
   'overall': 3.0,
   'summary': 'ok',
   'unixReviewTime': 1470096000,
   'predicted_genre': ['Crime', 'Drama', 'Family']},
  {'itemnum': 53138,
   'asin': 'B011MUA7N6',
   'reviewText': 'such brilliant idea to put all these in one collection, so I could give away some I had like six duplicates that are all on this collection..helps clear room of so much stuff..since I am collector of Sabbath films this helps a lot for me I need all room I can get',
   'overall': 5.0,
   'summary': 'good idea to have all movies in one collection on this disc instead of so many on vhs taking up room',
   'unixReviewTime': 1474070400,
   'predicted_genre': ['Biography', 'Family', 'History']},
  {'itemnum': 51440,
   'asin': 'B00S16H0DA',
   'reviewText': 'seemed ok film',
   'overall': 3.0,
   'summary': 'ok',
   'unixReviewTime': 1477008000,
   'predicted_genre': ['Drama', 'History', 'Romance']},
  {'itemnum': 11390,
   'asin': 'B000065U38',
   'reviewText': 'pretty good sorta funny I remember enjoying watching these as kid',
   'overall': 3.0,
   'summary': 'ok fun',
   'unixReviewTime': 1490227200,
   'predicted_genre': ['Comedy', 'Family']},
  {'itemnum': 46628,
   'asin': 'B00FA2CBH8',
   'reviewText': 'ok',
   'overall': 4.0,
   'summary': 'ok',
   'unixReviewTime': 1490227200,
   'predicted_genre': ['Biography', 'Drama', 'Family']},
  {'itemnum': '31231',
   'asin': 'B001RXDM36',
   'reviewText': '',
   'overall': '5',
   'summary': '',
   'unixReviewTime': 1740395188},
  {'itemnum': '39913',
   'asin': 'B0069RWAHY',
   'reviewText': '강찬미',
   'overall': '',
   'summary': '',
   'unixReviewTime': 1740395806},
  {'itemnum': '43993',
   'asin': 'B00BF4XJU8',
   'reviewText': '',
   'overall': '4',
   'summary': '',
   'unixReviewTime': 1740396042},
  {'itemnum': '15431',
   'asin': 'B0002PYSYC',
   'reviewText': '',
   'overall': '4',
   'summary': '',
   'unixReviewTime': 1740639301},
  {'itemnum': '22993',
   'asin': 'B000N47PAQ',
   'reviewText': '',
   'overall': '3',
   'summary': '',
   'unixReviewTime': 1740639889},
  {'itemnum': '45799',
   'asin': 'B00DW7IV5O',
   'reviewText': 'good',
   'overall': '',
   'summary': '',
   'unixReviewTime': 1740640100},
  {'itemnum': '49819',
   'asin': 'B00M0JTZVO',
   'reviewText': '',
   'overall': '4',
   'summary': '',
   'unixReviewTime': 1741137322},
  {'itemnum': '53036',
   'asin': 'B0112HPVEY',
   'reviewText': 'good',
   'overall': '',
   'summary': '',
   'unixReviewTime': 1741138001},
  {'itemnum': '53047',
   'asin': 'B0112HPVM6',
   'reviewText': '',
   'overall': '4',
   'summary': '',
   'unixReviewTime': 1741138286},
  {'itemnum': '54045',
   'asin': 'B017SZC2U0',
   'reviewText': '',
   'overall': '5',
   'summary': '',
   'unixReviewTime': 1741171205},
  {'itemnum': '52654',
   'asin': 'B00XZCIENK',
   'reviewText': '',
   'overall': '2',
   'summary': '',
   'unixReviewTime': 1741171351},
  {'itemnum': '52496',
   'asin': 'B00WV7TN80',
   'reviewText': '',
   'overall': '4',
   'summary': '',
   'unixReviewTime': 1741309932},
  {'itemnum': '53771',
   'asin': 'B01690GTK4',
   'reviewText': '',
   'overall': '4',
   'summary': '',
   'unixReviewTime': 1741316946},
  {'itemnum': '49696',
   'asin': 'B00LOCL8P4',
   'reviewText': '',
   'overall': '4',
   'summary': '',
   'unixReviewTime': 1741777623}],
 'userName': 'wyattandrew'}

In [19]:
items = mydb["item"]  # 컬렉션 이름

In [21]:
one_doc = items.find_one({"_id": "2"})

one_doc

{'_id': '2',
 'category': ['Movies & TV',
  'Genre for Featured Categories',
  'Faith & Spirituality'],
 'tech1': '',
 'description': ['Reunion [VHS]'],
 'fit': '',
 'title': 'Cathedral Quartet: A Reunion VHS',
 'also_buy': ['B00M45SW04'],
 'tech2': '',
 'brand': '',
 'feature': [],
 'rank': '679,734 in Movies & TV (',
 'also_view': [],
 'main_cat': 'Movies & TV',
 'similar_item': '',
 'date': '',
 'price': '.a-box-inner{background-color:#fff}#alohaBuyBoxWidget .selected{background-color:#fffbf3;border-color:#e77600;box-shadow:0 0 3px rgba(228,121,17,.5)}#alohaBuyBoxWidget .contract-not-available{color:gray}#aloha-cart-popover .aloha-cart{height:auto;overflow:hidden}#aloha-cart-popover #aloha-cartInfo{float:left}#aloha-cart-popover #aloha-cart-details{float:right;margin-top:1em}#aloha-cart-popover .deviceContainer{width:160px;float:left;padding-right:10px;border-right:1px solid #ddd}#aloha-cart-popover li:last-child{border-right:0}#aloha-cart-popover .aloha-device-title{height:3em;overflow:hidden}#aloha-cart-popover .aloha-thumbnail-container{height:100px;margin-bottom:1em;text-align:center}#aloha-cart-popover .aloha-price-container{text-align:center}#aloha-cart-popover .aloha-thumbnail-container img{height:inherit}#aloha-cart-popover .aloha-cart{border-top:1px solid #ddd;border-bottom:1px solid #ddd}#aloha-cart-popover #aloha-cart-info{margin-right:0}#alohaBuyBoxWidget .without-contract-subheading{margin-right:0}#aloha-bb-help-nodes .aloha-bb-contract-term-heading{color:gray;font-family:arial;margin-top:.5em;text-align:center;height:.7em;border-bottom:1px solid gray;margin-bottom:1.6em}#aloha-bb-help-nodes .aloha-bb-contract-term-heading span{background-color:#fff;padding:0 10px 0 10px}#alohaAvailabilityUS_feature_div .availability a{text-decoration:none}#alohaPricingWidget a{text-decoration:none}#alohaAvailabilityUS_feature_div .availability{margin-top:-4px;margin-bottom:0}#alohaBuyBoxWidget .select-transaction-alert .a-icon-alert{top:18px;left:3px}#alohaBuyBoxWidget .select-transaction-alert .a-alert-container{padding-left:39px;width:290px}#alohaBuyBoxUS_feature_div #alohaBuyBoxWidget .contract-container .contract-term-heading a{text-decoration:none}#alohaBuyBoxUS_feature_div #alohaBuyBoxWidget .annual-contract-box .a-icon-popover{display:none}#alohaBuyBoxUS_feature_div #alohaBuyBoxWidget .contract-container .annual-contract-box{cursor:pointer;cursor:hand}#alohaBuyBoxUS_feature_div #alohaBuyBoxWidget .aloha-buybox-price{font-size:15px}#alohaBuyBoxUS_feature_div #alohaBuyBoxWidget #linkOffSection a{text-decoration:none}#alohaBuyBoxUS_feature_div .lockedUsedBuyboxContainer{padding-left:3.5%}#alohaBuyBoxUS_feature_div .alohaBuyboxUtilsNoWrap{white-space:nowrap}.hidden{display:none}.simo-no-padding{padding:0}.carrier-reviews-cell{padding-left:10px}.carrier-reviews-bordered-cell{border:1px dotted #ccc}.carrier-reviews-selected-cell{background-color:#ffd}#aloha-carrier-compatibility-modal-table-description{margin-top:10px;margin-bottom:14px}.aloha-carrier-compatibility-sortable-header.carrier{min-width:97px}.aloha-carrier-compatibility-sortable-header.compatibility{min-width:156px}.aloha-carrier-compatibility-sortable-header div{float:left}.aloha-carrier-compatibility-sortable-header i.a-icon{margin-left:10px;margin-top:4px}#aloha-carrier-compatibility-overview-table.a-bordered.a-vertical-stripes td:nth-child(2n),#aloha-carrier-compatibility-overview-table.a-bordered.a-vertical-stripes th:nth-child(2n){background-color:initial}#aloha-carrier-compatibility-modal-table.a-bordered.a-vertical-stripes td:nth-child(2n),#aloha-carrier-compatibility-modal-table.a-bordered.a-vertical-stripes th:nth-child(2n){background-color:initial}#aloha-carrier-compatibility-table.a-bordered.a-vertical-stripes th:nth-child(2n),.aloha-carrier-compatibility-table.a-bordered.a-vertical-stripes td:nth-child(2n){background-color:transparent}.aloha-carrier-compatibility-column-gray{background-color:#f6f6f6}.aloha-carrier-compatibility-modal-table-row .aloha-carrier-compatibility-tech-text,.aloha-carrier-compatibility-modal-table-row .carrier-name,.aloha-carrier-compatibility-modal-table-row .carrier-rating-summary{min-height:27px;display:inline-block;cursor:default}.aloha-carrier-compatibility-modal-table-row .aloha-carrier-compatibility-tech-text:first-line,.aloha-carrier-compatibility-modal-table-row .carrier-name:first-line,.aloha-carrier-compatibility-modal-table-row .carrier-rating-summary:first-line{line-height:27px}.aloha-carrier-compatibility-modal-table-row .aloha-carrier-compatibility-icon{margin-top:6px}.aloha-carrier-compatibility-check-icon{width:30px;height:27px;background-position:-318px -35px;background-image:url(https://images-na.ssl-images-amazon.com/images/G/01/AUIClients/AmazonUIBaseCSS-sprite_2x-8e7ef370dc28a214b3f490c9620f4ac501d5a864._V2_.png);background-repeat:no-repeat;background-size:400px 650px;display:inline-block;vertical-align:top}.aloha-carrier-compatibility-hidden{display:none}.aloha-buybox-spaced-link{margin-top:12px;margin-bottom:7px;text-align:center}.popover-tab',
 'asin': '0005089549',
 'imageURL': [],
 'imageURLHighRes': [],
 'available_images': [],
 'predicted_genre': ['Comedy', 'Drama', 'Romance']}

In [15]:
items = pd.read_csv("item_detail.csv")
items["rating"]

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
86673    0.0
86674    0.0
86675    0.0
86676    0.0
86677    0.0
Name: rating, Length: 86678, dtype: float64

In [18]:
items["rating"] > 0

0        False
1        False
2        False
3        False
4        False
         ...
86673    False
86674    False
86675    False
86676    False
86677    False
Name: rating, Length: 86678, dtype: bool